trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt -y install cppcheck npm php php-xml && npm install -g handlebars-cmd
  displayName: 'Install script dependencies and Cppcheck'

- script: |
    git clone https://github.com/alexbrenes/vulnerable-code.git $HOME/vulnerable-code
  displayName: 'Clone repository'

- script: |
    mkdir $HOME/results
    cppcheck --xml-version=2 --enable=all --suppress=missingIncludeSystem . --output-file=$HOME/results/cppcheck-result.xml
  workingDirectory: $(HOME)/vulnerable-code
  displayName: 'Scan the repository'

- script: |
    export FILE=$HOME/results/cppcheck-result.xml
    php -r 'print(json_encode(simplexml_load_string(file_get_contents(getenv("FILE")), "SimpleXMLElement", LIBXML_NOCDATA)));' > $HOME/results/cppcheck-result.json
    tr -d '@' < $HOME/results/cppcheck-result.json > /tmp/cppcheck-result.json
    cat <<EOF > /tmp/junit-template.hbs
    <?xml version="1.0" encoding="UTF-8"?>
    <testsuites>
        <testsuite name="Cppcheck">
            <testcase name="{{location.attributes.file}}" classname="Cppcheck error" time="1.0">
                {{#each errors.error}}
                <failure message="{{attributes.msg}}" type="error:{{attributes.id}}">{{location.attributes.file}}:{{location.attributes.line}}:{{location.attributes.column}}: {{attributes.verbose}}</failure>
                {{/each}}
            </testcase>
        </testsuite>
    </testsuites>
    EOF
    ######
    cat <<EOF > /tmp/example.xml
    <?xml version="1.0" encoding="UTF-8"?>
    <testsuites time="15.682687">
        <testsuite name="Cppcheck" time="2.000">
            <testcase name="UnreadVariable" classname="Cppcheck error" time="1.000">
                <failure message="Variable &#x27;a[10]&#x27; is assigned a value that is never used." type="error:unreadVariable">bad-f/bad.cpp:4:11: Variable &#x27;a[10]&#x27; is assigned a value that is never used.</failure>
            </testcase>
            <testcase name="UnreadVariable2" classname="Cppcheck error" time="1.000">
                <failure message="Variable &#x27;a[10]&#x27; is assigned a value that is never used." type="error:unreadVariable">bad-f/bad.cpp:4:11: Variable &#x27;a[10]&#x27; is assigned a value that is never used.</failure>
            </testcase>
        </testsuite>
    </testsuites>
    EOF
    ######
    mkdir /tmp/results
    handlebars /tmp/cppcheck-result.json < /tmp/junit-template.hbs > /tmp/results/junit-cppcheck-result.xml
    cat /tmp/results/junit-cppcheck-result.xml
  displayName: 'Convert to JUnit'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '/tmp/example.xml'